version: '3.8'

services:
  db:
    image: postgres:15-alpine # Usando uma imagem PostgreSQL mais recente
    container_name: furry_friends_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER?ERRO_POSTGRES_USER_NAO_DEFINIDO_NO_ENV}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?ERRO_POSTGRES_PASSWORD_NAO_DEFINIDO_NO_ENV}
      POSTGRES_DB: ${POSTGRES_DB?ERRO_POSTGRES_DB_NAO_DEFINIDO_NO_ENV}
    ports:
      - "${POSTGRES_PORT?ERRO_POSTGRES_PORT_NAO_DEFINIDO_NO_ENV}:5432" # Mapeia a porta do container para o host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - furry_friends_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    build:
      context: ./furry-friends-agenda-backend # Caminho para o Dockerfile do backend
      dockerfile: Dockerfile
    container_name: furry_friends_backend
    restart: unless-stopped
    depends_on:
      db: # Espera o serviço db estar saudável antes de iniciar
        condition: service_healthy # Para um healthcheck mais robusto, o db precisaria de um script de healthcheck
    environment:
      NODE_ENV: production
      PORT: ${BACKEND_PORT?ERRO_BACKEND_PORT_NAO_DEFINIDO_NO_ENV}
      DATABASE_URL: ${DATABASE_URL?ERRO_DATABASE_URL_NAO_DEFINIDO_NO_ENV}
      JWT_SECRET: ${JWT_SECRET?ERRO_JWT_SECRET_NAO_DEFINIDO_NO_ENV}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN?ERRO_JWT_EXPIRES_IN_NAO_DEFINIDO_NO_ENV}
      # Prisma specific env var, if needed for migrations in entrypoint script
      # PRISMA_MIGRATE_EXPERIMENTAL: 'true' # Se for usar migrate no entrypoint
    ports:
      - "${BACKEND_PORT?ERRO_BACKEND_PORT_NAO_DEFINIDO_NO_ENV}:${BACKEND_PORT?ERRO_BACKEND_PORT_NAO_DEFINIDO_NO_ENV}"
    volumes:
      # Para desenvolvimento, você poderia montar o código-fonte:
      # - ./furry-friends-agenda-backend/src:/usr/src/app/src
      # - ./furry-friends-agenda-backend/prisma:/usr/src/app/prisma
      # Mas para produção, a imagem já contém o código buildado.
      # Se você tiver uploads de arquivos, precisará de um volume para eles.
    networks:
      - furry_friends_network
    # Adicionar um entrypoint/comando para rodar migrações automaticamente ao iniciar seria ideal para produção.
    # command: ["sh", "-c", "npx prisma migrate deploy && node dist/main.js"]

  frontend:
    build:
      context: ./furry-friends-agenda-app
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL?ERRO_VITE_API_BASE_URL_NAO_DEFINIDO_NO_ENV}
    container_name: furry_friends_frontend
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    networks:
      - furry_friends_network
    depends_on:
      backend:
        condition: service_healthy # Assuming backend has a healthcheck defined in its Dockerfile

networks:
  furry_friends_network:
    driver: bridge

volumes:
  postgres_data: # Volume nomeado para persistir dados do PostgreSQL 